# Generated by Django 5.0.7 on 2025-05-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purplex", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promptsubmission",
            name="problem",
        ),
        migrations.RemoveField(
            model_name="promptsubmission",
            name="user",
        ),
        migrations.DeleteModel(
            name="ProblemSet",
        ),
        migrations.DeleteModel(
            name="Problem",
        ),
        migrations.DeleteModel(
            name="PromptSubmission",
        ),
    ]
