# Generated by Django 5.0.7 on 2025-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("te", "Telugu"),
                    ("pa", "Punjabi"),
                    ("mr", "Marathi"),
                    ("kn", "Kannada"),
                    ("ta", "Tamil"),
                    ("ja", "Japanese"),
                    ("zh", "Chinese"),
                    ("pt", "Portuguese"),
                    ("vi", "Vietnamese"),
                    ("th", "Thai"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                ],
                default="en",
                help_text="User's preferred language for UI and AI feedback",
                max_length=5,
            ),
        ),
    ]
