# Generated by Django 5.2.11 on 2026-02-04 21:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_add_language_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When account deletion was requested (30-day grace period)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="deletion_scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When hard deletion is scheduled to occur",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="directory_info_visible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user's name/email are visible in course rosters",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("bn", "Bengali"),
                    ("te", "Telugu"),
                    ("pa", "Punjabi"),
                    ("mr", "Marathi"),
                    ("kn", "Kannada"),
                    ("ta", "Tamil"),
                    ("ja", "Japanese"),
                    ("zh", "Chinese"),
                    ("pt", "Portuguese"),
                    ("vi", "Vietnamese"),
                    ("th", "Thai"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("mi", "Māori"),
                ],
                default="en",
                help_text="User's preferred language for UI and AI feedback",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="AgeVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Optional — only collected if needed for verification",
                        null=True,
                    ),
                ),
                (
                    "is_minor",
                    models.BooleanField(
                        help_text="Under 18 (triggers DPDPA children's provisions)"
                    ),
                ),
                (
                    "is_child",
                    models.BooleanField(
                        help_text="Under 13 (triggers COPPA requirements)"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("self_declared", "Self-Declared"),
                            ("institutional", "Verified by Institution"),
                            ("parental", "Parent/Guardian Verified"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parental_consent_given", models.BooleanField(default=False)),
                (
                    "parental_consent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("parental_consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataPrincipalNominee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nominee_name", models.CharField(max_length=255)),
                ("nominee_email", models.EmailField(max_length=254)),
                ("nominee_relationship", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_nominee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataAccessAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_user_list", "Viewed User List"),
                            ("search_users", "Searched Users"),
                            ("export_research", "Exported Research Data"),
                            ("export_course", "Exported Course Data"),
                            ("view_student_detail", "Viewed Student Detail"),
                            ("change_role", "Changed User Role"),
                            ("delete_user", "Deleted User Account"),
                            ("view_submissions", "Viewed Submissions"),
                            ("data_export", "User Data Export"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_user_ids", models.JSONField(blank=True, default=list)),
                ("query_parameters", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("record_count", models.IntegerField(default=0)),
                (
                    "accessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["accessor", "-timestamp"],
                        name="users_app_d_accesso_685063_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="users_app_d_action_f5ed6e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_service", "Terms of Service"),
                            ("ai_processing", "AI Code Analysis"),
                            ("third_party_sharing", "Third-Party Data Sharing"),
                            ("research_use", "Research Data Use"),
                            ("behavioral_tracking", "Behavioral/Progress Tracking"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("policy_version", models.CharField(max_length=20)),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("registration", "At Registration"),
                            ("in_app", "In-App Prompt"),
                            ("institutional", "Via Institutional Agreement"),
                            ("parental", "Parental/Guardian Consent"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="users_app_u_user_id_10623e_idx",
                    ),
                    models.Index(
                        fields=["consent_type", "granted"],
                        name="users_app_u_consent_4b7d1a_idx",
                    ),
                ],
            },
        ),
    ]
