# Generated by Django 5.0.7 on 2025-06-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("instructor", "Instructor"),
                    ("user", "User"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
