# Generated by Django 5.0.7 on 2025-08-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("score", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "code_variations",
                    models.JSONField(
                        default=list, help_text="List of generated code variations"
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        default=list, help_text="Test results for each variation"
                    ),
                ),
                (
                    "passing_variations",
                    models.IntegerField(
                        default=0,
                        help_text="Number of variations that passed all tests",
                    ),
                ),
                (
                    "total_variations",
                    models.IntegerField(
                        default=0, help_text="Total number of variations generated"
                    ),
                ),
                (
                    "segmentation_passed",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the segmentation analysis passed the threshold (null if not applicable)",
                        null=True,
                    ),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True,
                        help_text="Total execution time in seconds",
                        null=True,
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        blank=True,
                        help_text="Time user spent on this attempt",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis",
                    models.JSONField(
                        help_text="Complete segmentation analysis including segments, mappings, and metadata"
                    ),
                ),
                (
                    "segment_count",
                    models.IntegerField(
                        db_index=True, help_text="Total number of segments identified"
                    ),
                ),
                (
                    "comprehension_level",
                    models.CharField(
                        choices=[
                            ("relational", "Relational"),
                            ("multi_structural", "Multi-structural"),
                        ],
                        db_index=True,
                        help_text="Binary classification based on segment count",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation",
                        to="submissions_app.promptsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentation Analysis",
                "verbose_name_plural": "Segmentation Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promptsubmission",
            index=models.Index(
                fields=["user", "problem", "course", "-submitted_at"],
                name="submissions_user_id_d74d16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptsubmission",
            index=models.Index(
                fields=["user", "problem_set", "course", "-submitted_at"],
                name="submissions_user_id_c7d356_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptsubmission",
            index=models.Index(
                fields=["course", "problem_set", "problem", "-score"],
                name="submissions_course__f0c2fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationresult",
            index=models.Index(
                fields=["comprehension_level", "segment_count"],
                name="submissions_compreh_aa7e75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationresult",
            index=models.Index(
                fields=["submission", "comprehension_level"],
                name="submissions_submiss_b9b468_idx",
            ),
        ),
    ]
