# Generated by Django 5.0.7 on 2025-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery task ID for async processing",
                max_length=255,
                null=True,
            ),
        ),
    ]
