# Generated by Django 5.0.7 on 2025-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="execution_time",
            field=models.FloatField(
                blank=True, help_text="Execution time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="promptsubmission",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Detailed feedback from test results"
            ),
        ),
        migrations.AddField(
            model_name="promptsubmission",
            name="passed_test_ids",
            field=models.JSONField(
                blank=True, default=list, help_text="IDs of test cases that passed"
            ),
        ),
        migrations.AddField(
            model_name="promptsubmission",
            name="time_spent",
            field=models.DurationField(
                blank=True, help_text="Time user spent on this attempt", null=True
            ),
        ),
    ]
