# Generated by Django 5.0.7 on 2025-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0002_promptsubmission_execution_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="promptsubmission",
            name="user_solution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
