# Generated by Django 5.0.7 on 2025-05-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0003_promptsubmission_firebase_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="submitted_by",
            field=models.CharField(
                blank=True,
                help_text="Username of the person who submitted this solution",
                max_length=255,
            ),
        ),
    ]
