# Generated by Django 5.0.7 on 2025-05-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0007_add_problem_set_context_to_progress"),
        ("submissions_app", "0004_promptsubmission_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="problem_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="problems_app.problemset",
            ),
        ),
    ]
