# Generated by Django 5.0.7 on 2025-06-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0009_remove_old_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promptsubmission",
            new_name="submissions_user_id_d74d16_idx",
            old_name="submissions_user_id_87c5f5_idx",
        ),
        migrations.RenameIndex(
            model_name="promptsubmission",
            new_name="submissions_user_id_c7d356_idx",
            old_name="submissions_user_id_8a9d12_idx",
        ),
        migrations.RenameIndex(
            model_name="promptsubmission",
            new_name="submissions_course__f0c2fe_idx",
            old_name="submissions_course__f4c5b3_idx",
        ),
        migrations.AlterField(
            model_name="promptsubmission",
            name="execution_time",
            field=models.FloatField(
                blank=True, help_text="Total execution time in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="promptsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
