# Generated by Django 5.0.7 on 2025-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0011_add_segmentation_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentationresult",
            name="comprehension_level",
            field=models.CharField(
                choices=[
                    ("relational", "Relational"),
                    ("multi_structural", "Multi-structural"),
                ],
                db_index=True,
                help_text="Binary classification based on segment count",
                max_length=20,
            ),
        ),
    ]
