# Generated by Django 5.0.7 on 2025-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions_app", "0013_convert_transitional_to_multi_structural"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptsubmission",
            name="segmentation_passed",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the segmentation analysis passed the threshold (null if not applicable)",
                null=True,
            ),
        ),
    ]
