# Generated by Django 5.0.7 on 2025-08-12 17:57

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_icons/"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color code", max_length=7
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Problem Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        help_text="User-defined course ID (e.g., CS101-FALL2024)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enrollment_open", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructed_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("eipl", "Explain in Plain Language (EiPL)"),
                            ("function_redefinition", "Function Redefinition"),
                        ],
                        default="eipl",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Problem description in markdown format"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Name of the function students implement",
                        max_length=50,
                    ),
                ),
                (
                    "function_signature",
                    models.TextField(
                        help_text="Function signature with parameter names and types"
                    ),
                ),
                (
                    "reference_solution",
                    models.TextField(help_text="Reference implementation"),
                ),
                (
                    "memory_limit",
                    models.PositiveIntegerField(
                        default=128, help_text="Memory limit in MB"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of tag strings"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "completion_threshold",
                    models.IntegerField(
                        default=100, help_text="Minimum score required for completion"
                    ),
                ),
                (
                    "completion_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object defining completion requirements",
                    ),
                ),
                (
                    "segmentation_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete segmentation configuration including threshold, examples, and settings",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum attempts allowed (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="unlocks", to="problems_app.problem"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="problems",
                        to="problems_app.problemcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="problem_set_icons/"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseProblemSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_required", models.BooleanField(default=True)),
                ("problem_set_version", models.IntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "problem_set")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="problem_sets",
            field=models.ManyToManyField(
                related_name="courses",
                through="problems_app.CourseProblemSet",
                to="problems_app.problemset",
            ),
        ),
        migrations.CreateModel(
            name="ProblemSetMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="problemset",
            name="problems",
            field=models.ManyToManyField(
                blank=True,
                related_name="problem_sets",
                through="problems_app.ProblemSetMembership",
                to="problems_app.problem",
            ),
        ),
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(auto_now_add=True)),
                ("completion_percentage", models.IntegerField()),
                ("problems_completed", models.IntegerField()),
                ("average_score", models.FloatField()),
                (
                    "time_spent_today",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputs", models.JSONField(help_text="Array of input arguments")),
                (
                    "expected_output",
                    models.JSONField(help_text="Expected output value"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description for this test case",
                        max_length=200,
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden test cases are not shown to students",
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Sample test cases are shown in problem description",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems_app.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserProblemSetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_problems", models.IntegerField(default=0)),
                ("completed_problems", models.IntegerField(default=0)),
                ("in_progress_problems", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("first_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.IntegerField(db_index=True, default=0),
                ),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("best_score", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("successful_attempts", models.IntegerField(default=0)),
                ("first_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_time_spent",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("hints_used", models.IntegerField(default=0)),
                ("consecutive_successes", models.IntegerField(default=0)),
                ("days_to_complete", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                (
                    "completion_percentage",
                    models.IntegerField(db_index=True, default=0),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="problems_app.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="problems_ap_user_id_26bd65_idx",
                    ),
                    models.Index(
                        fields=["course", "is_active"],
                        name="problems_ap_course__3ede88_idx",
                    ),
                ],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="ProblemHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint_type",
                    models.CharField(
                        choices=[
                            ("variable_fade", "Variable Fade"),
                            ("subgoal_highlight", "Subgoal Highlighting"),
                            ("suggested_trace", "Suggested Trace"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "min_attempts",
                    models.IntegerField(
                        default=3, help_text="Minimum attempts before hint is available"
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Hint-specific configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="problems_app.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["hint_type"],
                "unique_together": {("problem", "hint_type")},
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_id"], name="problems_ap_course__6e804a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "is_active"],
                name="problems_ap_instruc_346ce8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="problems_ap_is_dele_673a2e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problemsetmembership",
            unique_together={("problem_set", "problem")},
        ),
        migrations.AddIndex(
            model_name="progresssnapshot",
            index=models.Index(
                fields=["user", "-snapshot_date"], name="problems_ap_user_id_3cdbd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progresssnapshot",
            index=models.Index(
                fields=["user", "problem", "-snapshot_date"],
                name="problems_ap_user_id_0e21ed_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progresssnapshot",
            unique_together={("user", "problem", "problem_set", "snapshot_date")},
        ),
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together={("problem", "order")},
        ),
        migrations.AddIndex(
            model_name="userproblemsetprogress",
            index=models.Index(
                fields=["user", "course", "-last_activity"],
                name="problems_ap_user_id_9bb0e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userproblemsetprogress",
            index=models.Index(
                fields=["problem_set", "course", "-completion_percentage"],
                name="problems_ap_problem_eb04bd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userproblemsetprogress",
            unique_together={("user", "problem_set", "course")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "is_completed"],
                name="problems_ap_user_id_c1e8a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "status"],
                name="problems_ap_user_id_7c0c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["problem", "problem_set", "status"],
                name="problems_ap_problem_dfbf57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "-last_attempt"],
                name="problems_ap_user_id_95b230_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "course", "problem_set", "is_completed"],
                name="problems_ap_user_id_b5f0d1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "problem", "problem_set", "course")},
        ),
    ]
