# Generated by Django 5.0.7 on 2025-03-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('qid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('test_case_file', models.FileField(upload_to='testcases/')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='problem_set_icons/')),
                ('problems', models.ManyToManyField(related_name='problem_sets', to='problems_app.problem')),
            ],
        ),
    ]
