# Generated by Django 5.0.7 on 2025-09-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="requires_highlevel_comprehension",
            field=models.BooleanField(
                default=True,
                help_text="Whether EiPL problems require high-level comprehension for full credit",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="segmentation_threshold",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Maximum number of segments for high-level comprehension in EiPL problems",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="grade",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("partial", "Partially Complete"),
                    ("complete", "Complete"),
                ],
                db_index=True,
                default="incomplete",
                help_text="Grade based on correctness and high-levelness dimensions",
                max_length=20,
            ),
        ),
    ]
