# Generated by Django 5.0.7 on 2025-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='problem_set_icons/'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='problem_sets', to='problems_app.problem'),
        ),
    ]
