# Generated by Django 5.0.7 on 2025-05-26 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_sample_problems(apps, schema_editor):
    """Create sample problems in the new system"""
    Problem = apps.get_model('problems_app', 'Problem')
    ProblemCategory = apps.get_model('problems_app', 'ProblemCategory')
    TestCase = apps.get_model('problems_app', 'TestCase')
    ProblemSet = apps.get_model('problems_app', 'ProblemSet')
    ProblemSetMembership = apps.get_model('problems_app', 'ProblemSetMembership')
    
    # Create categories
    strings_cat = ProblemCategory.objects.create(
        name='String Manipulation',
        slug='strings',
        description='Problems involving string processing and manipulation',
        color='#3b82f6',
        order=1
    )
    
    # Create sample anagram problem
    anagram_problem = Problem.objects.create(
        slug='anagram-checker',
        title='Anagram Checker',
        description='''# Anagram Checker

Write a function that determines if two strings are anagrams of each other.

Two strings are anagrams if they contain the same characters with the same frequency, 
but possibly in a different order.

## Examples
- `is_anagram("listen", "silent")` → `True`
- `is_anagram("hello", "world")` → `False`
- `is_anagram("A", "a")` → `True` (case insensitive)

## Constraints
- The comparison should be case-insensitive
- Ignore spaces and punctuation
- String length: 1 ≤ len(str) ≤ 1000''',
        difficulty='beginner',
        function_name='is_anagram',
        function_signature='def is_anagram(str1: str, str2: str) -> bool:',
        reference_solution='''def is_anagram(str1, str2):
    # Remove spaces and convert to lowercase
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower()
    
    # Check if sorted characters are equal
    return sorted(str1) == sorted(str2)''',
        hints='''- Consider converting both strings to the same case
- Think about sorting the characters
- You might want to remove spaces first''',
        time_limit=30,
        memory_limit=128,
        estimated_time=15,
        tags=['strings', 'sorting', 'hash-map'],
        is_active=True
    )
    
    anagram_problem.categories.add(strings_cat)
    
    # Add test cases for anagram
    test_cases = [
        (['listen', 'silent'], True, 'Basic anagram test', False, True),
        (['hello', 'world'], False, 'Non-anagram test', False, True),
        (['A', 'a'], True, 'Case insensitive test', False, True),
        (['race', 'care'], True, 'Another anagram', False, False),
        (['rat', 'car'], False, 'Different lengths', False, False),
    ]
    
    for i, (inputs, expected, description, is_hidden, is_sample) in enumerate(test_cases):
        TestCase.objects.create(
            problem=anagram_problem,
            order=i,
            inputs=inputs,
            expected_output=expected,
            description=description,
            is_hidden=is_hidden,
            is_sample=is_sample
        )
    
    # Create palindrome problem
    palindrome_problem = Problem.objects.create(
        slug='palindrome-checker',
        title='Palindrome Checker',
        description='''# Palindrome Checker

Write a function that determines if a given string is a palindrome.

A palindrome is a word, phrase, number, or other sequence of characters that reads 
the same forward and backward.

## Examples
- `is_palindrome("racecar")` → `True`
- `is_palindrome("hello")` → `False`
- `is_palindrome("A man a plan a canal Panama")` → `True`

## Constraints
- The comparison should be case-insensitive
- Ignore spaces and punctuation
- String length: 1 ≤ len(str) ≤ 1000''',
        difficulty='beginner',
        function_name='is_palindrome',
        function_signature='def is_palindrome(s: str) -> bool:',
        reference_solution='''def is_palindrome(s):
    # Clean the string: remove spaces and convert to lowercase
    cleaned = ''.join(char.lower() for char in s if char.isalnum())
    
    # Check if it reads the same forwards and backwards
    return cleaned == cleaned[::-1]''',
        hints='''- Consider removing non-alphabetic characters
- Think about string reversal
- Two-pointer approach might be useful''',
        time_limit=30,
        memory_limit=128,
        estimated_time=10,
        tags=['strings', 'two-pointers'],
        is_active=True
    )
    
    palindrome_problem.categories.add(strings_cat)
    
    # Add test cases for palindrome
    palindrome_tests = [
        (['racecar'], True, 'Simple palindrome', False, True),
        (['hello'], False, 'Non-palindrome', False, True),
        (['A man a plan a canal Panama'], True, 'Complex palindrome with spaces', False, True),
        (['race a car'], False, 'Not a palindrome with spaces', False, False),
        ([''], True, 'Empty string', True, False),
    ]
    
    for i, (inputs, expected, description, is_hidden, is_sample) in enumerate(palindrome_tests):
        TestCase.objects.create(
            problem=palindrome_problem,
            order=i,
            inputs=inputs,
            expected_output=expected,
            description=description,
            is_hidden=is_hidden,
            is_sample=is_sample
        )
    
    # Create a problem set
    beginner_set = ProblemSet.objects.create(
        slug='string-fundamentals',
        title='String Fundamentals',
        description='Essential string manipulation problems for beginners',
        is_public=True
    )
    
    # Add problems to set
    ProblemSetMembership.objects.create(
        problem_set=beginner_set,
        problem=anagram_problem,
        order=0
    )
    
    ProblemSetMembership.objects.create(
        problem_set=beginner_set,
        problem=palindrome_problem,
        order=1
    )


def reverse_sample_problems(apps, schema_editor):
    """Remove sample data"""
    Problem = apps.get_model('problems_app', 'Problem')
    ProblemCategory = apps.get_model('problems_app', 'ProblemCategory')
    ProblemSet = apps.get_model('problems_app', 'ProblemSet')
    
    Problem.objects.all().delete()
    ProblemCategory.objects.all().delete()
    ProblemSet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems_app', '0002_alter_problemset_icon_alter_problemset_problems'),
    ]

    operations = [
        # Create new models while keeping old ones
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Problem Categories',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Rename old Problem model to avoid conflicts
        migrations.RenameModel(
            old_name='Problem',
            new_name='OldProblem',
        ),
        
        # Rename old ProblemSet model
        migrations.RenameModel(
            old_name='ProblemSet',
            new_name='OldProblemSet',
        ),
        
        # Create new Problem model
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Problem description in markdown format')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('function_name', models.CharField(help_text='Name of the function students implement', max_length=50)),
                ('function_signature', models.TextField(help_text='Function signature with parameter names and types')),
                ('reference_solution', models.TextField(help_text='Reference implementation')),
                ('hints', models.TextField(blank=True, help_text='Optional hints for students')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit in seconds')),
                ('memory_limit', models.PositiveIntegerField(default=128, help_text='Memory limit in MB')),
                ('estimated_time', models.PositiveIntegerField(default=15, help_text='Estimated solve time in minutes')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('categories', models.ManyToManyField(blank=True, related_name='problems', to='problems_app.problemcategory')),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(help_text='Array of input arguments')),
                ('expected_output', models.JSONField(help_text='Expected output value')),
                ('description', models.CharField(blank=True, help_text='Optional description for this test case', max_length=200)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases are not shown to students')),
                ('is_sample', models.BooleanField(default=False, help_text='Sample test cases are shown in problem description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems_app.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='problem_set_icons/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        migrations.CreateModel(
            name='ProblemSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_app.problem')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_app.problemset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        
        # Add through relationship
        migrations.AddField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='problem_sets', through='problems_app.ProblemSetMembership', to='problems_app.problem'),
        ),
        
        # Add unique constraints
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='problemsetmembership',
            unique_together={('problem_set', 'problem')},
        ),
        
        # Populate with sample data
        migrations.RunPython(create_sample_problems, reverse_sample_problems),
    ]