# Generated by Django 5.0.7 on 2025-05-26 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_sample_problems(apps, schema_editor):
    """Sample data creation moved to management command populate_sample_data.py"""
    pass


def reverse_sample_problems(apps, schema_editor):
    """Sample data creation moved to management command populate_sample_data.py"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems_app', '0002_alter_problemset_icon_alter_problemset_problems'),
    ]

    operations = [
        # Create new models while keeping old ones
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Problem Categories',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Rename old Problem model to avoid conflicts
        migrations.RenameModel(
            old_name='Problem',
            new_name='OldProblem',
        ),
        
        # Rename old ProblemSet model
        migrations.RenameModel(
            old_name='ProblemSet',
            new_name='OldProblemSet',
        ),
        
        # Create new Problem model
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Problem description in markdown format')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('function_name', models.CharField(help_text='Name of the function students implement', max_length=50)),
                ('function_signature', models.TextField(help_text='Function signature with parameter names and types')),
                ('reference_solution', models.TextField(help_text='Reference implementation')),
                ('hints', models.TextField(blank=True, help_text='Optional hints for students')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Time limit in seconds')),
                ('memory_limit', models.PositiveIntegerField(default=128, help_text='Memory limit in MB')),
                ('estimated_time', models.PositiveIntegerField(default=15, help_text='Estimated solve time in minutes')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('categories', models.ManyToManyField(blank=True, related_name='problems', to='problems_app.problemcategory')),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(help_text='Array of input arguments')),
                ('expected_output', models.JSONField(help_text='Expected output value')),
                ('description', models.CharField(blank=True, help_text='Optional description for this test case', max_length=200)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases are not shown to students')),
                ('is_sample', models.BooleanField(default=False, help_text='Sample test cases are shown in problem description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems_app.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='problem_set_icons/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        migrations.CreateModel(
            name='ProblemSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_app.problem')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_app.problemset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        
        # Add through relationship
        migrations.AddField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='problem_sets', through='problems_app.ProblemSetMembership', to='problems_app.problem'),
        ),
        
        # Add unique constraints
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='problemsetmembership',
            unique_together={('problem_set', 'problem')},
        ),
        
        # Populate with sample data
        migrations.RunPython(create_sample_problems, reverse_sample_problems),
    ]