# Generated by Django 5.0.7 on 2025-09-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="courseenrollment",
            name="idx_enrollment_lookup",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="idx_user_progress_lookup",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="idx_user_progress_set",
        ),
    ]
