# Generated by Django 5.0.7 on 2025-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0003_auto_20250526_2217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oldproblemset",
            name="problems",
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language (EiPL)"),
                    ("function_redefinition", "Function Redefinition"),
                ],
                default="eipl",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="OldProblem",
        ),
        migrations.DeleteModel(
            name="OldProblemSet",
        ),
    ]
