# Generated by Django 5.0.7 on 2025-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0004_remove_courseenrollment_idx_enrollment_lookup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="DEPRECATED - Not shown to students",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-extracted from reference solution",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_signature",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Auto-extracted from reference solution",
            ),
        ),
    ]
