# Generated by Django 5.0.7 on 2025-05-27 20:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems_app",
            "0004_remove_oldproblemset_problems_problem_problem_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="completion_criteria",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object defining completion requirements",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="completion_threshold",
            field=models.IntegerField(
                default=80, help_text="Minimum score required for completion"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="max_attempts",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum attempts allowed (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="unlocks", to="problems_app.problem"
            ),
        ),
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(auto_now_add=True)),
                ("completion_percentage", models.IntegerField()),
                ("problems_completed", models.IntegerField()),
                ("average_score", models.FloatField()),
                (
                    "time_spent_today",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-snapshot_date"],
                        name="problems_ap_user_id_3cdbd2_idx",
                    ),
                    models.Index(
                        fields=["user", "problem", "-snapshot_date"],
                        name="problems_ap_user_id_0e21ed_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "problem", "problem_set", "snapshot_date")
                },
            },
        ),
        migrations.CreateModel(
            name="UserProblemSetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_problems", models.IntegerField(default=0)),
                ("completed_problems", models.IntegerField(default=0)),
                ("attempted_problems", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("first_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.IntegerField(db_index=True, default=0),
                ),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="problems_ap_user_id_a776b4_idx",
                    ),
                    models.Index(
                        fields=["problem_set", "-completion_percentage"],
                        name="problems_ap_problem_41d24d_idx",
                    ),
                ],
                "unique_together": {("user", "problem_set")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("struggling", "Struggling"),
                            ("advancing", "Advancing"),
                            ("completed", "Completed"),
                            ("mastered", "Mastered"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("best_score", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("successful_attempts", models.IntegerField(default=0)),
                ("first_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_time_spent",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("hints_used", models.IntegerField(default=0)),
                ("consecutive_successes", models.IntegerField(default=0)),
                ("days_to_complete", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                (
                    "completion_percentage",
                    models.IntegerField(db_index=True, default=0),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_completed"],
                        name="problems_ap_user_id_023294_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="problems_ap_user_id_8761ae_idx"
                    ),
                    models.Index(
                        fields=["problem", "status"],
                        name="problems_ap_problem_867d51_idx",
                    ),
                    models.Index(
                        fields=["user", "-last_attempt"],
                        name="problems_ap_user_id_f1e562_idx",
                    ),
                ],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
