# Generated by Django 5.0.7 on 2025-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0005_problem_completion_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemset",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
