# Generated by Django 5.0.7 on 2025-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0005_simplify_problem_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="function_signature",
            field=models.TextField(
                help_text="Function signature with type hints for test case parsing"
            ),
        ),
    ]
