# Generated by Django 5.0.7 on 2025-05-28 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0006_alter_problemset_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprogress",
            name="problems_ap_user_id_023294_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="problems_ap_user_id_8761ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="problems_ap_problem_867d51_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="problems_ap_user_id_f1e562_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="problem_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems_app.problemset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "problem", "problem_set")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "is_completed"],
                name="problems_ap_user_id_c1e8a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "status"],
                name="problems_ap_user_id_7c0c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["problem", "problem_set", "status"],
                name="problems_ap_problem_dfbf57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "problem_set", "-last_attempt"],
                name="problems_ap_user_id_95b230_idx",
            ),
        ),
    ]
