# Generated by Django 5.0.7 on 2025-05-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0007_add_problem_set_context_to_progress"),
    ]

    operations = [
        # Add index on Problem.slug for fast lookups
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_idx'),
        ),
        # Add index on ProblemSet.slug for fast lookups
        migrations.AddIndex(
            model_name='problemset',
            index=models.Index(fields=['slug'], name='problems_ps_slug_idx'),
        ),
        # Add composite index on UserProgress for common queries
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'problem_set'], name='user_probset_idx'),
        ),
        # Add index on ProblemSetMembership for ordered queries
        migrations.AddIndex(
            model_name='problemsetmembership',
            index=models.Index(fields=['problem_set', 'order'], name='probset_order_idx'),
        ),
    ]
