# Generated by Django 5.0.7 on 2025-11-25 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0007_consolidate_problem_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="mcq_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of {id, text, is_correct} objects for MCQ problems",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instructed_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language (EiPL)"),
                    ("mcq", "Multiple Choice Question"),
                ],
                default="eipl",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="problems_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="problems_app.problem"
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="problem_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="problems_app.problemset",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
