# Generated by Django 5.0.7 on 2025-11-29 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0008_add_mcq_options_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="problems_ap_is_acti_3f0326_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_active", "difficulty"],
                name="problems_ap_is_acti_a47ed8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="problems_ap_created_9a5ade_idx",
            ),
        ),
    ]
