# Generated by Django 5.0.7 on 2025-11-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0009_add_problem_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="prompt_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Config for prompt problems: {image_url, image_alt_text}",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language (EiPL)"),
                    ("mcq", "Multiple Choice Question"),
                    ("prompt", "Prompt (Image-based EiPL)"),
                ],
                default="eipl",
                max_length=30,
            ),
        ),
    ]
