# Generated by Django 5.0.7 on 2025-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0010_add_prompt_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Question text for MCQ, optional for code problems",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_signature",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Function signature with type hints for test case parsing",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="reference_solution",
            field=models.TextField(
                blank=True, default="", help_text="Reference implementation"
            ),
        ),
    ]
