# Generated by Django 5.0.7 on 2025-05-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0010_remove_time_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="problem",
            name="problems_pr_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="problemset",
            name="problems_ps_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="problemsetmembership",
            name="probset_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprogress",
            name="user_probset_idx",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="hints",
        ),
    ]
