# Generated by Django 5.0.7 on 2025-06-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0011_remove_hints_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseProblemSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_required", models.BooleanField(default=True)),
                ("problem_set_version", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="problemset",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        help_text="User-defined course ID (e.g., CS101-FALL2024)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enrollment_open", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructed_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems_app.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "problem", "problem_set", "course")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "course", "problem_set", "is_completed"],
                name="problems_ap_user_id_b5f0d1_idx",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="problems_app.course",
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseproblemset",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems_app.course"
            ),
        ),
        migrations.AddField(
            model_name="courseproblemset",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="problems_app.problemset",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="problem_sets",
            field=models.ManyToManyField(
                related_name="courses",
                through="problems_app.CourseProblemSet",
                to="problems_app.problemset",
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["user", "is_active"], name="problems_ap_user_id_26bd65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["course", "is_active"], name="problems_ap_course__3ede88_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="courseproblemset",
            unique_together={("course", "problem_set")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_id"], name="problems_ap_course__6e804a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "is_active"],
                name="problems_ap_instruc_346ce8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="problems_ap_is_dele_673a2e_idx",
            ),
        ),
    ]
