# Generated by Django 5.0.7 on 2025-12-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("problems_app", "0011_make_code_fields_optional_for_mcq"),
    ]

    operations = [
        migrations.CreateModel(
            name="McqProblem",
            fields=[
                (
                    "problem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="problems_app.problem",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question/prompt shown to students"),
                ),
                (
                    "grading_mode",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("llm", "LLM-graded"),
                            ("manual", "Manual"),
                        ],
                        default="deterministic",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Array of {id, text, is_correct, explanation} objects",
                    ),
                ),
                (
                    "allow_multiple",
                    models.BooleanField(
                        default=False, help_text="Allow selecting multiple answers"
                    ),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(
                        default=False, help_text="Randomize option order per attempt"
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ Problem",
                "verbose_name_plural": "MCQ Problems",
            },
            bases=("problems_app.problem",),
        ),
        migrations.AddField(
            model_name="problem",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language (EiPL)"),
                    ("mcq", "Multiple Choice Question"),
                    ("prompt", "Prompt (Image-based EiPL)"),
                ],
                default="eipl",
                help_text="LEGACY: Will be replaced by polymorphic type detection",
                max_length=30,
            ),
        ),
    ]
