# Generated by Django 5.0.7 on 2025-12-02 01:17
"""
Data migration to convert existing MCQ problems to polymorphic McqProblem model.

This migration:
1. Finds all Problem records with problem_type='mcq'
2. Creates corresponding McqProblem records with the same primary key
3. Copies description -> question_text, mcq_options -> options
4. Sets the polymorphic_ctype on the base Problem record
"""

import json

from django.db import migrations


def migrate_mcq_problems(apps, schema_editor):
    """Migrate existing MCQ problems to polymorphic McqProblem model."""
    from django.db import connection

    Problem = apps.get_model("problems_app", "Problem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get the ContentType for McqProblem and Problem
    # Need to get or create since this may be first time
    mcq_content_type, _ = ContentType.objects.get_or_create(
        app_label="problems_app", model="mcqproblem"
    )
    problem_content_type, _ = ContentType.objects.get_or_create(
        app_label="problems_app", model="problem"
    )

    # Find all MCQ problems in the base Problem table
    mcq_problems = Problem.objects.filter(problem_type="mcq")
    print(f"Found {mcq_problems.count()} MCQ problems to migrate")

    # Use raw SQL to insert McqProblem records without touching the parent
    with connection.cursor() as cursor:
        for problem in mcq_problems:
            # Serialize options to JSON string
            options_json = json.dumps(problem.mcq_options or [])
            question_text = problem.description or ""

            # Insert into McqProblem table
            cursor.execute(
                """
                INSERT INTO problems_app_mcqproblem
                (problem_ptr_id, question_text, grading_mode, options, allow_multiple, shuffle_options)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (problem_ptr_id) DO NOTHING
            """,
                [
                    problem.pk,
                    question_text,
                    "deterministic",
                    options_json,
                    False,
                    False,
                ],
            )

            # Update polymorphic_ctype on the Problem
            cursor.execute(
                """
                UPDATE problems_app_problem
                SET polymorphic_ctype_id = %s
                WHERE id = %s
            """,
                [mcq_content_type.pk, problem.pk],
            )

            print(f"  Migrated: {problem.title}")

    # Set polymorphic_ctype for non-MCQ problems (they stay as base Problem for now)
    non_mcq_problems = Problem.objects.filter(
        problem_type__in=["eipl", "prompt"], polymorphic_ctype__isnull=True
    )
    with connection.cursor() as cursor:
        for problem in non_mcq_problems:
            cursor.execute(
                """
                UPDATE problems_app_problem
                SET polymorphic_ctype_id = %s
                WHERE id = %s AND polymorphic_ctype_id IS NULL
            """,
                [problem_content_type.pk, problem.pk],
            )


def reverse_migrate_mcq_problems(apps, schema_editor):
    """Reverse migration - delete McqProblem records and clear polymorphic_ctype."""
    from django.db import connection

    with connection.cursor() as cursor:
        # Delete all McqProblem records (leaves the base Problem records intact)
        cursor.execute("DELETE FROM problems_app_mcqproblem")

        # Clear polymorphic_ctype on all Problem records
        cursor.execute("UPDATE problems_app_problem SET polymorphic_ctype_id = NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0012_convert_to_polymorphic"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(migrate_mcq_problems, reverse_migrate_mcq_problems),
    ]
