# Generated by Django 5.0.7 on 2025-12-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0013_migrate_mcq_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="mcq_options",
        ),
        migrations.AlterField(
            model_name="problem",
            name="completion_criteria",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_signature",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="problem",
            name="memory_limit",
            field=models.PositiveIntegerField(default=128),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language (EiPL)"),
                    ("mcq", "Multiple Choice Question"),
                    ("prompt", "Prompt (Image-based EiPL)"),
                ],
                default="eipl",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="prompt_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="problem",
            name="reference_solution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="problem",
            name="requires_highlevel_comprehension",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="segmentation_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="problem",
            name="segmentation_threshold",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
