# Generated by Django 5.0.7 on 2025-06-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0013_add_course_to_progress"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userproblemsetprogress",
            name="problems_ap_user_id_a776b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="userproblemsetprogress",
            name="problems_ap_problem_41d24d_idx",
        ),
        migrations.RenameIndex(
            model_name="userproblemsetprogress",
            new_name="problems_ap_user_id_9bb0e8_idx",
            old_name="problems_ap_user_id_course_last_idx",
        ),
        migrations.RenameIndex(
            model_name="userproblemsetprogress",
            new_name="problems_ap_problem_eb04bd_idx",
            old_name="problems_ap_problem_course_comp_idx",
        ),
    ]
