# Generated by Django 5.0.7 on 2025-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems_app",
            "0014_remove_userproblemsetprogress_problems_ap_user_id_a776b4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="completion_threshold",
            field=models.IntegerField(
                default=100, help_text="Minimum score required for completion"
            ),
        ),
    ]
