# Generated by Django 5.0.7 on 2025-06-14 14:14

from django.db import migrations


def update_completion_thresholds(apps, schema_editor):
    Problem = apps.get_model('problems_app', 'Problem')
    # Update all problems with threshold of 80 to 100
    Problem.objects.filter(completion_threshold=80).update(completion_threshold=100)


def reverse_completion_thresholds(apps, schema_editor):
    Problem = apps.get_model('problems_app', 'Problem')
    # Reverse: Update all problems with threshold of 100 back to 80
    Problem.objects.filter(completion_threshold=100).update(completion_threshold=80)


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0015_update_completion_threshold_to_100"),
    ]

    operations = [
        migrations.RunPython(update_completion_thresholds, reverse_completion_thresholds),
    ]
