# Generated by Django 5.0.7 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0015_create_eipl_prompt_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eiplproblem",
            name="function_name",
            field=models.CharField(
                blank=True,
                help_text="Auto-extracted from reference_solution if not provided",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="function_signature",
            field=models.TextField(
                help_text="Function signature with type hints for test case parsing"
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="llm_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="LLM settings: {model, temperature, max_tokens}",
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="memory_limit",
            field=models.PositiveIntegerField(
                default=128, help_text="Memory limit in MB for code execution"
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="reference_solution",
            field=models.TextField(
                help_text="Reference implementation for test validation"
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="requires_highlevel_comprehension",
            field=models.BooleanField(
                default=True,
                help_text="Require high-level comprehension for full credit",
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="segmentation_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Segmentation settings: {enabled, min_segments, examples}",
            ),
        ),
        migrations.AlterField(
            model_name="eiplproblem",
            name="segmentation_threshold",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Max segments for high-level comprehension (fewer = better)",
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="function_name",
            field=models.CharField(
                blank=True,
                help_text="Auto-extracted from reference_solution if not provided",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="function_signature",
            field=models.TextField(
                help_text="Function signature with type hints for test case parsing"
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="image_alt_text",
            field=models.CharField(
                blank=True, help_text="Alt text for accessibility", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="image_url",
            field=models.URLField(help_text="URL of the problem image"),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="llm_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="LLM settings: {model, temperature, max_tokens}",
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="memory_limit",
            field=models.PositiveIntegerField(
                default=128, help_text="Memory limit in MB for code execution"
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="reference_solution",
            field=models.TextField(
                help_text="Reference implementation for test validation"
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="requires_highlevel_comprehension",
            field=models.BooleanField(
                default=True,
                help_text="Require high-level comprehension for full credit",
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="segmentation_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Segmentation settings: {enabled, min_segments, examples}",
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="segmentation_threshold",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Max segments for high-level comprehension (fewer = better)",
            ),
        ),
    ]
