# Generated by Django 5.0.7 on 2025-06-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0016_update_existing_completion_thresholds"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint_type",
                    models.CharField(
                        choices=[
                            ("variable_fade", "Variable Fade"),
                            ("subgoal_highlight", "Subgoal Highlighting"),
                            ("input_suggestion", "Input Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "min_attempts",
                    models.IntegerField(
                        default=3, help_text="Minimum attempts before hint is available"
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Hint-specific configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="problems_app.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["hint_type"],
                "unique_together": {("problem", "hint_type")},
            },
        ),
    ]
