# Generated by Django 5.0.7 on 2025-06-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0018_update_hint_type_to_suggested_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemhint",
            name="hint_type",
            field=models.CharField(
                choices=[
                    ("variable_fade", "Variable Fade"),
                    ("subgoal_highlight", "Subgoal Highlighting"),
                    ("suggested_trace", "Suggested Trace"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
