# Generated by Django 5.0.7 on 2025-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0019_alter_problemhint_hint_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproblemsetprogress",
            old_name="partially_complete_problems",
            new_name="in_progress_problems",
        ),
    ]
