# Generated by Django 5.1.15 on 2025-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0020_add_probeable_spec_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Problem description in markdown format",
            ),
        ),
        migrations.AlterField(
            model_name="probeablecodeproblem",
            name="reference_solution",
            field=models.TextField(
                help_text="Reference implementation for test validation"
            ),
        ),
        migrations.AlterField(
            model_name="probeablespecproblem",
            name="reference_solution",
            field=models.TextField(
                help_text="Reference implementation for test validation"
            ),
        ),
    ]
