# Generated by Django 5.0.7 on 2025-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0020_rename_partially_complete_to_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="segmentation_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete segmentation configuration including threshold, examples, and settings",
            ),
        ),
    ]
