# Generated by Django 5.1.15 on 2025-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0022_add_claim_predicate_to_refute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debugfixproblem",
            options={
                "verbose_name": "Debug and Fix Code",
                "verbose_name_plural": "Debug and Fix Code Problems",
            },
        ),
        migrations.AlterModelOptions(
            name="eiplproblem",
            options={
                "verbose_name": "Explain in Plain Language",
                "verbose_name_plural": "Explain in Plain Language Problems",
            },
        ),
        migrations.AlterModelOptions(
            name="mcqproblem",
            options={
                "verbose_name": "Multiple Choice Question",
                "verbose_name_plural": "Multiple Choice Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="probeablecodeproblem",
            options={
                "verbose_name": "Probeable Problem (Code)",
                "verbose_name_plural": "Probeable Problems (Code)",
            },
        ),
        migrations.AlterModelOptions(
            name="probeablespecproblem",
            options={
                "verbose_name": "Probeable Problem (Explanation)",
                "verbose_name_plural": "Probeable Problems (Explanation)",
            },
        ),
        migrations.AlterModelOptions(
            name="refuteproblem",
            options={
                "verbose_name": "Refute: Find Counterexample",
                "verbose_name_plural": "Refute: Find Counterexample Problems",
            },
        ),
        migrations.AddField(
            model_name="courseproblemset",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional due date for this problem set in this course",
                null=True,
            ),
        ),
    ]
