# Generated by Django 5.1.15 on 2025-12-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0023_add_due_date_to_courseproblemset"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseproblemset",
            name="deadline_type",
            field=models.CharField(
                choices=[
                    ("none", "No Deadline"),
                    ("soft", "Soft Deadline"),
                    ("hard", "Hard Deadline"),
                ],
                default="none",
                help_text="none: no enforcement, soft: allow late with flag, hard: block after due",
                max_length=10,
            ),
        ),
    ]
