# Generated by Django 5.1.15 on 2025-12-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0025_fix_polymorphic_ctype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptproblem',
            name='image_alt_text',
            field=models.TextField(blank=True, help_text='Alt text for accessibility (up to 1500 characters)'),
        ),
    ]
