# Generated by Django 5.2.11 on 2026-02-16 14:05

from django.db import migrations


def populate_course_instructors(apps, schema_editor):
    """Copy existing Course.instructor FK into CourseInstructor rows."""
    Course = apps.get_model("problems_app", "Course")
    CourseInstructor = apps.get_model("problems_app", "CourseInstructor")

    rows = []
    for course in Course.objects.select_related("instructor").iterator():
        rows.append(
            CourseInstructor(
                course=course,
                user=course.instructor,
                role="primary",
            )
        )

    if rows:
        CourseInstructor.objects.bulk_create(rows, ignore_conflicts=True)


def reverse_populate(apps, schema_editor):
    """No-op reverse: the CourseInstructor table will be dropped by schema rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0027_create_course_instructor"),
    ]

    operations = [
        migrations.RunPython(populate_course_instructors, reverse_populate),
    ]
