# Generated by Django 5.2.11 on 2026-03-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0029_make_instructor_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
    ]
