# Generated by Django 5.2.11 on 2026-03-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0030_drop_instructor_fk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together=set(),
        ),
    ]
