# Generated by Django 5.2.11 on 2026-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0031_remove_testcase_order_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debugfixproblem",
            name="allow_complete_rewrite",
        ),
    ]
