# Generated by Django 5.2.11 on 2026-03-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0031_remove_testcase_order_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemhint",
            name="hint_type",
            field=models.CharField(
                choices=[
                    ("variable_fade", "Variable Fade"),
                    ("subgoal_highlight", "Subgoal Highlighting"),
                    ("suggested_trace", "Suggested Trace"),
                    ("counterexample", "Counterexample"),
                ],
                max_length=20,
            ),
        ),
    ]
