# Generated by Django 5.2.12 on 2026-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0032_remove_debugfix_allow_complete_rewrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptproblem",
            name="display_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mode-specific display data. terminal: {schema_version, runs: [{label?, interactions: [{type: input|output, text}]}]}. function_table: {schema_version, calls: [{args: [], return_value: any}]}",
            ),
        ),
        migrations.AddField(
            model_name="promptproblem",
            name="display_mode",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("terminal", "Terminal Interaction"),
                    ("function_table", "Function Call Table"),
                ],
                default="image",
                help_text="How the problem stimulus is presented to students",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promptproblem",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the problem image (required when display_mode='image')",
            ),
        ),
    ]
