# Generated by Django 5.0.7 on 2025-09-21 22:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("direct_code", "Direct Code Submission"),
                            ("eipl", "Explain in Plain Language"),
                            ("function_redef", "Function Redefinition"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "raw_input",
                    models.TextField(
                        help_text="Original user input (code or natural language)"
                    ),
                ),
                (
                    "processed_code",
                    models.TextField(
                        blank=True, help_text="Final code that was executed"
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "memory_used_mb",
                    models.FloatField(
                        blank=True, help_text="Peak memory usage in MB", null=True
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        db_index=True, default=0, help_text="Overall score (0-100)"
                    ),
                ),
                ("passed_all_tests", models.BooleanField(db_index=True, default=False)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("partial", "Partial Success"),
                            ("complete", "Complete Success"),
                        ],
                        db_index=True,
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        blank=True, help_text="Time spent on this attempt", null=True
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_submissions",
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_submissions",
                        to="problems_app.problem",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_submissions",
                        to="problems_app.problemset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentationAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_count", models.IntegerField(db_index=True)),
                (
                    "comprehension_level",
                    models.CharField(
                        choices=[
                            ("relational", "Relational (Good)"),
                            ("multi_structural", "Multi-structural (Needs Work)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "segments",
                    models.JSONField(
                        help_text="List of identified segments with descriptions"
                    ),
                ),
                (
                    "code_mappings",
                    models.JSONField(help_text="Mapping of segments to code lines"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Model confidence in segmentation (0-1)"
                    ),
                ),
                ("processing_time_ms", models.IntegerField()),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=50)),
                (
                    "feedback_message",
                    models.TextField(help_text="Constructive feedback for the student"),
                ),
                (
                    "suggested_improvements",
                    models.JSONField(
                        default=list, help_text="Specific suggestions for improvement"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HintActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation_order",
                    models.IntegerField(
                        help_text="Order in which hints were activated"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Request"),
                            ("auto_attempts", "Auto After N Attempts"),
                            ("auto_time", "Auto After Time"),
                            ("instructor", "Instructor Provided"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "viewed_duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="How long hint was displayed", null=True
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True, help_text="User feedback on helpfulness", null=True
                    ),
                ),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.problemhint",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_activations",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["activation_order"],
            },
        ),
        migrations.CreateModel(
            name="CodeVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_index",
                    models.IntegerField(help_text="Index of this variation (0-based)"),
                ),
                ("generated_code", models.TextField()),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False, help_text="Was this the best variation?"
                    ),
                ),
                ("tests_passed", models.IntegerField(default=0)),
                ("tests_total", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=50)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("generation_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_variations",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["variation_index"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_automated", models.BooleanField(default=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("praise", "Praise"),
                            ("suggestion", "Suggestion"),
                            ("correction", "Correction"),
                            ("hint", "Hint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_visible_to_student", models.BooleanField(default=True)),
                (
                    "provided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_order",
                    models.IntegerField(help_text="Order in which test was executed"),
                ),
                ("passed", models.BooleanField(db_index=True, default=False)),
                (
                    "input_values",
                    models.JSONField(help_text="Actual input values used"),
                ),
                ("expected_output", models.JSONField(help_text="Expected output")),
                (
                    "actual_output",
                    models.JSONField(
                        blank=True, help_text="What the code produced", null=True
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No Error"),
                            ("wrong_output", "Wrong Output"),
                            ("runtime_error", "Runtime Error"),
                            ("timeout", "Timeout"),
                            ("memory_exceeded", "Memory Limit Exceeded"),
                            ("syntax_error", "Syntax Error"),
                        ],
                        default="none",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full traceback for debugging", null=True
                    ),
                ),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("memory_used_kb", models.IntegerField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_executions",
                        to="submissions.submission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems_app.testcase",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "problem", "course", "-submitted_at"],
                name="submissions_user_id_0a9ee4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "problem_set", "course", "-submitted_at"],
                name="submissions_user_id_79c8be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["course", "problem_set", "-score"],
                name="submissions_course__3c62a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["submission_type", "execution_status"],
                name="submissions_submiss_6ba447_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationanalysis",
            index=models.Index(
                fields=["comprehension_level", "segment_count"],
                name="submissions_compreh_aee6dc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hintactivation",
            unique_together={("submission", "hint")},
        ),
        migrations.AlterUniqueTogether(
            name="codevariation",
            unique_together={("submission", "variation_index")},
        ),
        migrations.AddIndex(
            model_name="testexecution",
            index=models.Index(
                fields=["submission", "passed"], name="submissions_submiss_30f624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testexecution",
            index=models.Index(
                fields=["test_case", "passed"], name="submissions_test_ca_cd35d4_idx"
            ),
        ),
    ]
