# Generated by Django 5.0.7 on 2025-09-22 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecution",
            name="code_variation",
            field=models.ForeignKey(
                blank=True,
                help_text="Which code variation this test was run against (for EiPL)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_executions",
                to="submissions.codevariation",
            ),
        ),
    ]
