# Generated by Django 5.0.7 on 2025-09-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_testexecution_code_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="comprehension_level",
            field=models.CharField(
                choices=[
                    ("high-level", "High-level/Relational"),
                    ("low-level", "Low-level/Multistructural"),
                    ("not_evaluated", "Not Evaluated"),
                ],
                default="not_evaluated",
                help_text="Comprehension level based on segmentation analysis",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_correct",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the submission passes all test cases",
            ),
        ),
    ]
