# Generated by Django 5.0.7 on 2025-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_add_database_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentationanalysis",
            name="passed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether segmentation meets the threshold (segment_count <= threshold)",
            ),
        ),
        migrations.AlterField(
            model_name="codevariation",
            name="model_used",
            field=models.CharField(default="gpt-5", max_length=50),
        ),
        migrations.AlterField(
            model_name="segmentationanalysis",
            name="model_used",
            field=models.CharField(default="gpt-5", max_length=50),
        ),
    ]
