# Generated by Django 5.0.7 on 2025-11-25 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0008_add_mcq_options_field"),
        ("submissions", "0005_add_passed_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="new_submissions",
                to="problems_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="new_submissions",
                to="problems_app.problem",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="new_submissions",
                to="problems_app.problemset",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("direct_code", "Direct Code Submission"),
                    ("eipl", "Explain in Plain Language"),
                    ("mcq", "Multiple Choice Question"),
                    ("function_redef", "Function Redefinition"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
