# Generated by Django 5.1.15 on 2025-12-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_add_celery_task_id_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_late",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if submitted after soft deadline",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("eipl", "Explain in Plain Language"),
                    ("mcq", "Multiple Choice Question"),
                    ("prompt", "Prompt (Image-based)"),
                    ("refute", "Refute (Counterexample)"),
                    ("debug_fix", "Debug Fix"),
                    ("probeable_code", "Probeable Code"),
                    ("probeable_spec", "Probeable Spec"),
                    ("direct_code", "Direct Code Submission"),
                    ("function_redef", "Function Redefinition"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
