# Generated by Django 5.1.15 on 2025-12-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_add_deadline_enforcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="is_late",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="True if submitted after soft deadline",
            ),
        ),
    ]
