# Generated by Django 5.2.11 on 2026-03-25 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0032_remove_debugfix_allow_complete_rewrite"),
        ("submissions", "0010_rename_related_name_to_submissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-separated namespace: probe.execute, hint.view, refute.attempt, etc.",
                        max_length=80,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Event-specific data. Schema varies by event_type: probe.execute: {input: str, output: str, probe_index: int}; hint.view: {hint_type: str, problem_slug: str}; refute.attempt: {counterexample: dict, result: dict}",
                    ),
                ),
                (
                    "anonymous_user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hash (16 chars) via AnonymizationService, set at creation. Survives user deletion for research correlation.",
                        max_length=16,
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Payload schema version for forward-compatible evolution",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional deduplication key, prevents duplicate recording on retry",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL preserves event when course deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to="problems_app.course",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL preserves event when problem deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to="problems_app.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL preserves event for research when user deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="submissions_user_id_3a1e6c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"],
                        name="submissions_event_t_84e35b_idx",
                    ),
                    models.Index(
                        fields=["course", "event_type", "-timestamp"],
                        name="submissions_course__8bf05f_idx",
                    ),
                ],
            },
        ),
    ]
